spring.application.name=PrototypeAi
server.tomcat.basedir=C:/Users/Ridah/AppData/Local/Temp
logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %white++(%msg%n)}

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/prototypeai
spring.datasource.username=admin
spring.datasource.password=root

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# LOG SQL (debug)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.docker.compose.lifecycle-management=start-and-stop



# Config jwt
jwt.secretKey = jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4
jwt.tokenValiditySeconds = 3600
jwt.issuer = prototypeAi